name: DockerImage2Harbor

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: core.harbor.onmetal.de/onmetal/netdata-ipam

jobs:
  push:
    runs-on: self-hosted
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        env:
          GIT_USER: ${{secrets.GIT_USER}}
          GIT_PASSWORD: ${{secrets.GIT_PASSWORD}}
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest --build-arg GOPRIVATE="github.com/onmetal/*" --build-arg GIT_USER=${GIT_USER} --build-arg GIT_PASSWORD=${GIT_PASSWORD}

      - name: Login to harbor
        uses: docker/login-action@v2
        with:
          registry: core.harbor.onmetal.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy to Docker registry
        run: docker push $IMAGE_NAME:latest
